### ISSUE TITLE
How to compile to x86 for CSGO?

### ISSUE THREAD

**Issue by L1ghtingBolt** [sy1ntexx/egui-d3d11#1]
CSGO is x86 and also is using d3d9. Any way to use this?

EDIT: I used this command:
```cargo build --release --target i686-pc-windows-msvc --target-dir ../target`
But this just doesn't build:
`error[E0463]: can't find crate for `core`
  |
  = note: the `i686-pc-windows-msvc` target may not be installed
  = help: consider downloading the target with `rustup target add i686-pc-windows-msvc`

error[E0463]: can't find crate for `compiler_builtins`

For more information about this error, try `rustc --explain E0463`.
error: could not compile `cfg-if` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `core`
   --> C:\Users\gerar\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:192:1
    |
192 | extern crate core as std;
    | ^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
    |
    = note: the `i686-pc-windows-msvc` target may not be installed
    = help: consider downloading the target with `rustup target add i686-pc-windows-msvc`

error: cannot find macro `stringify` in this scope
   --> C:\Users\gerar\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:470:24
    |
470 |         f.debug_struct(stringify!(ScopeGuard))
    |                        ^^^^^^^^^

error: cannot find attribute `derive` in this scope
   --> C:\Users\gerar\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:212:3
    |
212 | #[derive(Debug)]
    |   ^^^^^^

error[E0433]: failed to resolve: use of undeclared type `ManuallyDrop`
   --> C:\Users\gerar\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:319:20
    |
319 |             value: ManuallyDrop::new(v),
    |                    ^^^^^^^^^^^^ use of undeclared type `ManuallyDrop`

error[E0433]: failed to resolve: use of undeclared type `ManuallyDrop`
   --> C:\Users\gerar\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:320:21
    |
320 |             dropfn: ManuallyDrop::new(dropfn),
    |                     ^^^^^^^^^^^^ use of undeclared type `ManuallyDrop`

error[E0433]: failed to resolve: use of undeclared crate or module `ptr`
   --> C:\Users\gerar\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:352:25
    |
352 |             let value = ptr::read(&*guard.value);
    |                         ^^^ use of undeclared crate or module `ptr`

error[E0433]: failed to resolve: use of undeclared crate or module `ptr`
   --> C:\Users\gerar\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:357:27
    |
357 |             let _dropfn = ptr::read(&*guard.dropfn);
    |                           ^^^ use of undeclared crate or module `ptr`

error[E0433]: failed to resolve: use of undeclared crate or module `mem`
   --> C:\Users\gerar\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:358:13
    |
358 |             mem::forget(guard);
    |             ^^^ use of undeclared crate or module `mem`

error[E0433]: failed to resolve: use of undeclared crate or module `ptr`
   --> C:\Users\gerar\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:456:14
    |
456 |             (ptr::read(&*self.value), ptr::read(&*self.dropfn))
    |              ^^^ use of undeclared crate or module `ptr`

error[E0433]: failed to resolve: use of undeclared crate or module `ptr`
   --> C:\Users\gerar\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:456:39
    |
456 |             (ptr::read(&*self.value), ptr::read(&*self.dropfn))
    |                                       ^^^ use of undeclared crate or module `ptr`

error[E0433]: failed to resolve: use of undeclared crate or module `fmt`
   --> C:\Users\gerar\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:464:15
    |
464 | impl<T, F, S> fmt::Debug for ScopeGuard<T, F, S>
    |               ^^^ use of undeclared crate or module `fmt`

error[E0433]: failed to resolve: use of undeclared crate or module `fmt`
   --> C:\Users\gerar\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:465:14
    |
465 |     where T: fmt::Debug,
    |              ^^^ use of undeclared crate or module `fmt`

error[E0433]: failed to resolve: use of undeclared crate or module `fmt`
   --> C:\Users\gerar\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:469:27
    |
469 |     fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
    |                           ^^^ use of undeclared crate or module `fmt`

error[E0433]: failed to resolve: use of undeclared crate or module `fmt`
   --> C:\Users\gerar\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:469:46
    |
469 |     fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
    |                                              ^^^ use of undeclared crate or module `fmt`

error[E0405]: cannot find trait `FnOnce` in this scope
   --> C:\Users\gerar\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:299:14
    |
299 |     where F: FnOnce(T),
    |              ^^^^^^ not found in this scope

error[E0412]: cannot find type `ManuallyDrop` in this scope
   --> C:\Users\gerar\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:302:12
    |
302 |     value: ManuallyDrop<T>,
    |            ^^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `ManuallyDrop` in this scope
   --> C:\Users\gerar\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:303:13
    |
303 |     dropfn: ManuallyDrop<F>,
    |             ^^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `PhantomData` in this scope
   --> C:\Users\gerar\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:305:15
    |
305 |     strategy: PhantomData<fn(S) -> S>,
    |               ^^^^^^^^^^^ not found in this scope

error[E0405]: cannot find trait `FnOnce` in this scope
   --> C:\Users\gerar\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:309:14
    |
309 |     where F: FnOnce(T),
    |              ^^^^^^ not found in this scope

error[E0425]: cannot find value `PhantomData` in this scope
   --> C:\Users\gerar\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:321:23
    |
321 |             strategy: PhantomData,
    |                       ^^^^^^^^^^^ not found in this scope

error[E0405]: cannot find trait `FnOnce` in this scope
   --> C:\Users\gerar\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:368:14
    |
368 |     where F: FnOnce(T)
    |              ^^^^^^ not found in this scope

error[E0405]: cannot find trait `Sync` in this scope
   --> C:\Users\gerar\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:422:22
    |
422 | unsafe impl<T, F, S> Sync for ScopeGuard<T, F, S>
    |                      ^^^^ not found in this scope

error[E0405]: cannot find trait `Sync` in this scope
   --> C:\Users\gerar\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:423:14
    |
423 |     where T: Sync,
    |              ^^^^ not found in this scope

error[E0405]: cannot find trait `FnOnce` in this scope
   --> C:\Users\gerar\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:424:14
    |
424 |           F: FnOnce(T),
    |              ^^^^^^ not found in this scope

error[E0405]: cannot find trait `Deref` in this scope
   --> C:\Users\gerar\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:428:15
    |
428 | impl<T, F, S> Deref for ScopeGuard<T, F, S>
    |               ^^^^^ not found in this scope

error[E0405]: cannot find trait `FnOnce` in this scope
   --> C:\Users\gerar\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:429:14
    |
429 |     where F: FnOnce(T),
    |              ^^^^^^ not found in this scope

error[E0405]: cannot find trait `DerefMut` in this scope
   --> C:\Users\gerar\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:439:15
    |
439 | impl<T, F, S> DerefMut for ScopeGuard<T, F, S>
    |               ^^^^^^^^ not found in this scope

error[E0405]: cannot find trait `FnOnce` in this scope
   --> C:\Users\gerar\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:440:14
    |
440 |     where F: FnOnce(T),
    |              ^^^^^^ not found in this scope

error[E0405]: cannot find trait `Drop` in this scope
   --> C:\Users\gerar\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:448:15
    |
448 | impl<T, F, S> Drop for ScopeGuard<T, F, S>
    |               ^^^^ not found in this scope

error[E0405]: cannot find trait `FnOnce` in this scope
   --> C:\Users\gerar\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:449:14
    |
449 |     where F: FnOnce(T),
    |              ^^^^^^ not found in this scope

error[E0405]: cannot find trait `FnOnce` in this scope
   --> C:\Users\gerar\.cargo\registry\src\github.com-1ecc6299db9ec823\scopeguard-1.1.0\src\lib.rs:466:14
    |
466 |           F: FnOnce(T),
    |              ^^^^^^ not found in this scope```

**Comment by sy1ntexx** [comment]
Unfortunately, I don't think it's possible to use this backend with csgo. This project is supposed to be used inside of a dll and you can't make d3d11 work with d3d9 but you can try to make an external overlay and draw from there. However, there are other projects that make this process easier.
