### ISSUE TITLE
Helop

### ISSUE THREAD

**Issue by Alleexxi** [sy1ntexx/egui-d3d11#4]
Hello, sorry if i am dumb but i can't get the example to work. maybe because the game is 32bit but i would really appreciate it if someone could help me. I hope this is the right place to ask for help

**Comment by sy1ntexx** [comment]
In order to compile for 32bit you need to use `--target i686-pc-windows-msvc` but I have never tested this project on any 32bit games

**Comment by Alleexxi** [comment]
> 

It looks like the patterns are different/outdated for 32bit games (using the ones in the example)

**Comment by Alleexxi** [comment]
![grafik](https://user-images.githubusercontent.com/66967403/184171142-72724c64-0e29-492c-9cdc-cf9263e68aac.png)

**Comment by sy1ntexx** [comment]
You'll need to find your own patterns for Present and ResizeBuffers in 32bit dlls or find other methods to hook these methods.
